### ISSUE TITLE
Fans control

### ISSUE THREAD

**Issue by priyanshuarora595** [stayboogy/stayboogy_Ventura-Hackintosh_Dell-Inspiron-5570#1]
I have a dell inspiron 15 5577 laptop running macOS Monterey. Its pretty smooth but i have 2 issues : 
1. I am not able to control the fans by  any method. I am using VirtualSMC but i cant control fans. I have tried many apps. 
2. after waking from sleep, The fans automatically starts spinning. Although the temperature is showing 46 degrees only still the fans are not stopping. 

please guide how did you controlled this?
Thank you

**Comment by stayboogy** [comment]
I am using the newer, appropriate kexts for SMC control and have this properly configured in my config.plist, and then macsfancontrol will work.  Basically most of the kexts out there littered around the web are garbage. like 90% of them. find good ones from my EFI folder here, or elsewhere here on Github only, not anything from opencore, unibeast, etc.

i'm closing this because this has nothing to do with an issue with my work

**Comment by stayboogy** [comment]
also, this requires proper DSDT patching. also, your fans are spinning after waking from sleep because you do not have sleep and wake properly fixed, again DSDT patching.
